name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3
  permission_handler: ^11.0.3 # Required to handle permissions
  cupertino_icons: ^1.0.6 # For Cupertino icons
  shared_preferences: ^2.0.15
  sqflite: ^2.0.0+4
  path_provider: ^2.0.12
  fl_chart: ^0.69.0
  http: ^1.2.2
  pedometer: ^4.0.2
  intl: ^0.17.0
  path: ^1.9.0
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  # Add your assets here if you need them
  assets:
    - assets/images/upper-body.jpg
    - assets/images/Jogging.jpg
    - assets/images/Yoga.png
    - assets/images/Jogging.jpg
    - assets/images/ob-1.png
    - assets/images/ob-1.1.png
    - assets/images/ob-2.1.png
    - assets/images/ob-3.1.png
    - assets/images/Login_1.png
    - assets/images/Muscle.png
    - assets/images/Loose.png
    - assets/images/pushup.jpg


    # Fonts configuration if needed
  fonts:
     - family: Poppins
       fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
        
 
